https://movie-database-imdb-alternative.p.rapidapi.com/?rapidapi-key=61cd997641mshecc536a501fa685p1ce10djsn9b8b0710bd78&page=1&r=json&s=avengers

{"X-RapidAPI-Host": "movie-database-imdb-alternative.p.rapidapi.com"}